### ISSUE TITLE
okhttp client instrumentation

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/meta#11]
Hello,

I have done okhttp client [1] instrumentation. I would like to move it to contrib org if there is interest for it. 

[1]: https://github.com/square/okhttp

**Comment by bensigelman** [comment]
@pavolloffay sounds good to me – where is the instrumentation at the moment? What sounds good re a repo name?

**Comment by pavolloffay** [comment]
It's not pushed anywhere. I can create a repo if you would like to have a look. 

Repo name:
`java-okhttp` ?

**Comment by bensigelman** [comment]
Created: https://github.com/opentracing-contrib/java-okhttp/invitations

**Comment by pavolloffay** [comment]
Closing, it is released and referenced from /meta.
