### ISSUE TITLE
Request to transfer opentracing-java-aws under opentracing-contrib

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/meta#17]
Please help me to transfer java-aws (https://github.com/malafeev/opentracing-java-aws)
under opentracing-contrib

**Comment by yurishkuro** [comment]
Could you please provide more details about what this lib is actually instrumenting, so that we can pick an appropriate repo name? AWS is a huge ecosystem.

**Comment by malafeev** [comment]
it is an java aws sdk instrumentation (s3 client, dynamodb client etc).
@bhs already created repo: https://github.com/opentracing-contrib/java-aws-sdk
thanks

**Comment by bhs** [comment]
@yurishkuro as I understand it, the idea is to provide interceptor-style tracing for the AWS SDKs. IMO it's worth batching those into a single git repo since there is a lot of redundancy.
