### ISSUE TITLE
Request to transfer opentracing-java-jdbc under opentracing-contrib

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/meta#18]
@bhs 
Please create repository java-jdbc under opentracing-contrib.
I would like to transfer OpenTracing JDBC Instrumentation (https://github.com/malafeev/opentracing-java-jdbc).

**Comment by bhs** [comment]
@malafeev, what's your opinion about the existence of both JDBC and JDBI instrumentation? Are they both warranted? Should one replace the other? Should they be part of the same repo? If so, which?

**Comment by malafeev** [comment]
@bhs jdbc is the most low level api.
jdbi works above jdbc.
Although jdbc instrumentation can replace jdbi instrumentation I suppose that in some cases 
jdbi instrumentation is convenient to use.

**Comment by malafeev** [comment]
@bhs I propose to create java-jdbc repo with jdbc instrumentation.
and deprecate `jdbi` (pointing to `jdbc`)

**Comment by pavolloffay** [comment]
nit: I don't know how jdbc/jdbi instrumentations works, but sometimes it is possible to start spans at lower levels and add some meaningful tags/logs in higher levels. e.g. web filter and spring interceptor. But I don't know if this is the case.

**Comment by malafeev** [comment]
@pavolloffay jdbc/jdbi instrumentation works almost the same way as instrumentation of http clients: start span before request and finish span when response is received. 
Difference that request/response protocol is not http but jdbc.

**Comment by bhs** [comment]
https://github.com/opentracing-contrib/java-jdbc/invitations
