### ISSUE TITLE
Request to transfer opentracing-java-mongo under opentracing-contrib

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/meta#20]
@bhs
Please create repository java-mongo-driver under opentracing-contrib.
I would like to transfer OpenTracing Mongo Driver Instrumentation (https://github.com/malafeev/opentracing-java-mongo).

**Comment by bhs** [comment]
So this one *does* seem like a `-client` instead of a `-driver`, correct? (per #21)

**Comment by malafeev** [comment]
I would prefer `-driver` although main object is `MongoClient`
```xml
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>${mongo.driver.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-async</artifactId>
            <version>${mongo.driver.version}</version>
        </dependency>
```

**Comment by bhs** [comment]
@malafeev https://github.com/opentracing-contrib/java-mongo-client/invitations

I realize you preferred `-driver`, but I did some light googling and it looks like "client" is the term that's preferred in the Mongo universe, so I've gone with that. If you feel strongly, let me know and we can debate it. :)

**Comment by bhs** [comment]
hmmmm... I did some more googling and have reversed my opinion :)

I will change the repo name: https://github.com/opentracing-contrib/java-mongo-driver/invitations

**Comment by malafeev** [comment]
:)
