### ISSUE TITLE
Request to transfer opentracing-java-cassandra under opentracing-contrib

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/meta#21]
@bhs
Please create repository java-cassandra-driver under opentracing-contrib.
I would like to transfer OpenTracing Cassandra Driver Instrumentation (https://github.com/malafeev/opentracing-java-cassandra).

**Comment by bhs** [comment]
Sorry, basic question, @malafeev: is this "driver" basically the cassandra client sdk? (Seems that way) If so, are there multiple competing cassandra clients/drivers out there in the world?

I realize that cassandra uses the "driver" terminology, but part of me wants to call this `java-cassandra-client`...

**Comment by malafeev** [comment]
@bhs it is low level DataStax Driver instrumentation.
Others drivers depends on  DataStax Driver. They use it on  transport level.
Therefore there is no need for instrumentation of others drivers.

http://cassandra.apache.org/doc/latest/getting_started/drivers.html

**Comment by malafeev** [comment]
I don't think that it should be a client. It is like jdbc - the most possible low level instrumentation which can be used by others clients/drivers

**Comment by bhs** [comment]
https://github.com/opentracing-contrib/java-cassandra-driver/invitations

thanks!
