### ISSUE TITLE
Request to transfer opentracing-java-elasticsearch under opentracing-contrib  

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/meta#22]
@bhs
Please create repository java-elasticsearch-client under opentracing-contrib.
I would like to transfer OpenTracing  Elasticsearch Client Instrumentation (https://github.com/malafeev/opentracing-java-elasticsearch).

**Comment by bhs** [comment]
https://github.com/opentracing-contrib/java-elasticsearch-client/invitations

Thanks!
