### ISSUE TITLE
Request to transfer opentracing-java-rabbitmq under opentracing-contrib

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/meta#23]
@bhs
Please create repository java-rabbitmq-client under opentracing-contrib.
I would like to transfer OpenTracing RabbitMQ Client Instrumentation (https://github.com/malafeev/opentracing-java-rabbitmq).

**Comment by bhs** [comment]
https://github.com/opentracing-contrib/java-rabbitmq-client/invitations

Thank you!
