### ISSUE TITLE
Request to transfer java-tracerresolver under opentracing-contrib

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/meta#24]
@bhs 
Can we create a 'java-tracerresolver' under opentracing-contrib to host the `ServiceLoader` integration that was in the contrib `GlobalTracer` but has not made it into the util package?

I'd like to transfer the following repo: https://github.com/sjoerdtalsma/java-tracerresolver
See discussion in https://github.com/opentracing-contrib/java-globaltracer/issues/7#issuecomment-292228434

cc: @objectiser

**Comment by bhs** [comment]
@sjoerdtalsma done: https://github.com/opentracing-contrib/java-tracerresolver/invitations

The name is a mouthful, but I wasn't able to think of an alternative suggestion I actually like. :)
