### ISSUE TITLE
Java: OpenTracing aware executors/runnables...

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/meta#27]
OT API 0.30.0 contains in-process span management. Often it is required to use OT aware executor service. We could create a contrib library or move it directly to `opentracing-util`.

cc @bhs @yurishkuro

**Comment by sjoerdtalsma** [comment]
I am :+1: for adding an OT aware executor service to `opentracing-util`.

In the mean time, may I point out a small lib you can use that is also capable of transferring other contexts?
 - [opentracing-span-propagation](https://github.com/talsma-ict/context-propagation/tree/master/opentracing-span-propagation)

_My appologies if this is not appropriate here.._

**Comment by bhs** [comment]
@pavolloffay I absolutely think we should have add OT-aware executors/etc to opentracing-contrib.

@sjoerdtalsma thank you for the pointer.

**Comment by pavolloffay** [comment]
> @pavolloffay I absolutely think we should have add OT-aware executors/etc to opentracing-contrib.

+1 

Repo name proposals:
* java-concurrent 
* java-executors
* java-lang-concurrent

Executor is in `java.util.concurrent` package.

**Comment by bhs** [comment]
@pavolloffay @sjoerdtalsma great. I created `java-concurrent` and sent invites so it shows up in your respective inboxes.

https://github.com/opentracing-contrib/java-concurrent/invitations

**Comment by pavolloffay** [comment]
done, the first version is out.
