### ISSUE TITLE
New repository for "java-metrics"

### ISSUE THREAD

**Issue by objectiser** [opentracing-contrib/meta#28]
Could you please create a new ot-contrib repo called "java-metrics".

This repository will contain a mechanism for intercepting reported spans to derive metrics that can be reported to metrics systems, with initial support for Prometheus. The intention is to report metrics using a standard set of labels, but also support adding custom labels.

If this approach is successful, then hopefully a similar approach can be used for other OT language clients.

**Comment by yurishkuro** [comment]
@objectiser which interception mechanism are you planning to use, a wrapper or an observer?

Repo created https://github.com/opentracing-contrib/java-metrics/

**Comment by objectiser** [comment]
Thanks @yurishkuro.

The initial version will use a wrapper, but that is managed internally, and intention is to move to observer when available.

**Comment by yurishkuro** [comment]
Sounds good. I would suggest starting with a PR for the README that describes the naming scheme for the metrics, as that is something we've been trying out in Jaeger clients and it's not the most obvious problem to solve, esp. when building support for different transports. One possible approach is [here](https://github.com/yarpc/yarpc-go/blob/dev/internal/observability/graph.go#L209), although I have a couple of concerns with it.
