### ISSUE TITLE
Java web filter instrumentation

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/meta#3]
Hello,

I would like to contribute java filter [1] instrumentation. The codebase would be probably very small (one, two classes). Could we consider move it to [2]?  I have also some work going on for spring instrumentation It's again very small repo. 

[1]: http://docs.oracle.com/javaee/6/api/javax/servlet/Filter.html
[2]: https://github.com/opentracing-contrib/java-jaxrs

**Comment by bensigelman** [comment]
@pavolloffay thanks!

The filter instrumentation sounds :100:. Moving it to https://github.com/opentracing-contrib/java-jaxrs seems at odds with the name `java-jaxrs` since this piece would be more general. We could either do a micro-repo or establish something like `java-misc`, `java-core`, `java-basics` or something like that...

**Comment by pavolloffay** [comment]
I'm for:
* micro repo `java-web-servlet-filter`
* move it to `java-jaxrs` which would require probably change the name. I bit like this as both instrumentations are for java spec.
* `java-[misc|core|basics]` I cannot think of other stuff which would be there?

**Comment by bensigelman** [comment]
@pavolloffay so maybe we rename `java-jaxrs` as `java-jdk` (I can't think of a better name for the standard libs included with Java, can you?), then move this instrumentation over there. Thoughts?

**Comment by pavolloffay** [comment]
The question is if we want to aim all java standard instrumentations (se, ee, me) (I'm wondering whether there would be some instrumentation for java se, me).

* `java-javaee`, `java-ee`, `java-javax` 
* `java-jdk`, `java-platform` which could include all standard isntrumentations.

@yurishkuro @wu-sheng

**Comment by yurishkuro** [comment]
my 2c - don't go for generic names, stick with micro-repos (unless there's large overhead with publishing micro-repos)

**Comment by pavolloffay** [comment]
I'm fine with micro repo.

**Comment by wu-sheng** [comment]
+1 micro-repos. 

All in one, like java-ee or java-jdk is not easy to understand, and hard to tell the diff from other contrib in java-platform.

**Comment by pavolloffay** [comment]
Here is the repo for web-filter. https://github.com/pavolloffay/opentracing-java-web-servlet-filter

**Comment by bensigelman** [comment]
The main per-repo overhead (IMO) is the silly but incredibly useful TravisCI maven stuff, per https://github.com/opentracing-contrib/java-globaltracer/pull/6/files and similar.

Also, in addition to repos, we need to figure out artifact naming. See https://github.com/opentracing-contrib/java-globaltracer/pull/6/files#r95784904 for context.

@pavolloffay @sjoerdtalsma looking at https://github.com/opentracing-contrib/java-globaltracer/pull/6/files#diff-600376dffeb79835ede4a0b285078036R24 to make this concrete: `io.opentracing.contrib.` seems like an obvious prefix. I could imagine all contrib artifacts cohabitating in that namespace (i.e., without additional qualifiers like `.globaltracer.foo`), XOR we can do `io.opentracing.contrib.globaltracer.opentracing-globaltracer`, but that feels a lot like stuttering to me.

**Comment by bensigelman** [comment]
@pavolloffay https://github.com/opentracing-contrib/java-web-servlet-filter/invitations

**Comment by sjoerdtalsma** [comment]
@bensigelman ok, I'll change `io.opentracing.contrib.globaltracer:opentracing-globaltracer` maven artifact to `io.opentracing.contrib:opentracing-globaltracer` in the PR you mentioned above.
(https://github.com/opentracing-contrib/java-globaltracer/pull/6)

**Comment by bensigelman** [comment]
@sjoerdtalsma sounds good, thanks.

**Comment by pavolloffay** [comment]
I'm closing it. It is released and referenced from /meta.
