### ISSUE TITLE
New repo for java-observer

### ISSUE THREAD

**Issue by objectiser** [opentracing-contrib/meta#30]
Would be good to have a repo, equivalent to the recent go-observer, to start discussing a similar API for Java.

**Comment by pavolloffay** [comment]
Do we want to go with the same approach as in go? Or incorporate it into the main API?

**Comment by objectiser** [comment]
I think same approach as the go repo - develop the API and mature it, before then potentially moving to the main API.

**Comment by yurishkuro** [comment]
https://github.com/opentracing-contrib/java-observer
