### ISSUE TITLE
p6spy instrumentation

### ISSUE THREAD

**Issue by hypnoce** [opentracing-contrib/meta#31]
In opentracing contrib there is already a [jdbc instrumentation](https://github.com/opentracing-contrib/java-jdbc). I think there is a place for p6spy since people may already have an environment setup with this jdbc proxy.
Here is the main repo : https://github.com/hypnoce/opentracing-p6spy 
Let me know if you have any comments.

I'm missing Bintray and Sonatype access as described here : https://github.com/opentracing-contrib/meta/blob/master/guide_java.md 

Thanks for your help !

**Comment by tedsuo** [comment]
@malafeev Can you review?

This looks useful to me. I'm wondering if there should be an expectation that this produces the same data as https://github.com/opentracing-contrib/java-jdbc, or if there is anything interesting about how they are different.

@bhs can you add bintray/sonatype for this?

**Comment by malafeev** [comment]
**java-jdbc** and **p6spy** instrumentation should produce similar data.
I took idea from **p6spy** when implemented **java-jdbc**.
In case you are using some specific **p6spy** features it could be useful.

**Comment by hypnoce** [comment]
@malafeev let me know if you need any change on my side regarding span decoration

**Comment by hypnoce** [comment]
@bhs my Bintray user is [hypnoce](https://bintray.com/hypnoce)

**Comment by hypnoce** [comment]
Hi @all any news ? Maybe you are overloaded :).

**Comment by malafeev** [comment]
I'm OK to add it to contrib

**Comment by hypnoce** [comment]
@malafeev I added the same `traceWithActiveSpanOnly` option for feature consistency. Let me know if you are ok with this.

**Comment by malafeev** [comment]
great @hypnoce

**Comment by malafeev** [comment]
@hypnoce I created https://github.com/opentracing-contrib/java-p6spy 
but I don't have permissions to grant you access to bintray/sonatype
@bhs did it for me.

**Comment by bhs** [comment]
@hypnoce you should have a bintray invite. Sorry for the delay! I have a crazy inbox :-/

**Comment by hypnoce** [comment]
@bhs no worries I can understand :)

**Comment by hypnoce** [comment]
Hi all,

just committed the first implementation : https://github.com/opentracing-contrib/java-p6spy 

Thanks very much for your time !

**Comment by hypnoce** [comment]
version 0.0.1 released : http://search.maven.org/#search%7Cga%7C1%7Copentracing-p6spy 
Thanks all for your help !

**Comment by bhs** [comment]
@hypnoce excellent, thank you!
