### ISSUE TITLE
Spring web integration

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/meta#4]
Hello, 

I have done some integration work with spring web. 

Here is repository:
https://github.com/pavolloffay/opentracing-spring-boot-instrumentation repo is empty but there is pending PR. It's quite similar to java-web-filter instrumentation.

@bensigelman could you please create a repository for this? 

`java-spring-web` or `java-spring-web-interceptor`...? The first one is more generic in case we add something.

**Comment by bensigelman** [comment]
@pavolloffay delighted to create the repo. I asked on Gitter, but will repeat here: would `java-spring-boot` make sense? Or better to make it `web`-specific? If the latter, what about `java-spring-boot-web`? (Just trying my best to get this right the first time)

**Comment by mabn** [comment]
Right now it has "spring boot" in various places, but I don't think that the actual implementation depends on spring-boot (just the tests). I'd suggest to make it more generic by changing dependency to spring-web.
As for spring-boot - ideally there would be java-spring-boot-autoconfiguration which integrates various libraries with spring boot, with optional dependencies.

**Comment by pavolloffay** [comment]
Yes, this should be for spring web in general (not spring boot specific). 

Possible repo names: 
`java-spring-web`, `java-spring-web-interceptor`..

> Right now it has "spring boot" in various places 

This will be removed/renamed.

**Comment by bensigelman** [comment]
@pavolloffay great, done... please visit https://github.com/opentracing-contrib/java-spring-web/invitations. thanks again!

**Comment by bensigelman** [comment]
I closed this but have re-opened... let's not close until the artifact is available and there's a pointer from this meta repo or the OT.io site.

**Comment by pavolloffay** [comment]
I'm closing it, artifact is released and linked to ot-contrib/meta
