### ISSUE TITLE
Repository for csharp-logging

### ISSUE THREAD

**Issue by Falco20019** [opentracing-contrib/meta#51]
I'm one of the maintainers of [jaegertracing/jaeger-client-csharp](https://github.com/jaegertracing/jaeger-client-csharp/) and [opentracing-contrib/csharp-grpc](https://github.com/opentracing-contrib/csharp-grpc). I would like to add the code base using `Microsoft.Extensions.Logging` to the `opentracing-contrib` project.

We have this functionality in a non-flexible way already in [opentracing-contrib/csharp-netcore](https://github.com/opentracing-contrib/csharp-netcore) which I would create a PR for to unify the usage. The idea is, to have `Microsoft.Extensions.Logging` support for any .NET Core framework, without having to use the full [opentracing-contrib/csharp-netcore](https://github.com/opentracing-contrib/csharp-netcore) or even dependency injection. So splitting it would be the best way in my opinion.

/CC @yurishkuro

**Comment by yurishkuro** [comment]
Created https://github.com/opentracing-contrib/csharp-logging
