### ISSUE TITLE
Request to transfer caddy-opentracing under opentracing-contrib

### ISSUE THREAD

**Issue by tra4less** [opentracing-contrib/meta#54]
@bhs 
Please create repository caddy-opentracing under opentracing-contrib.
I would like to transfer Caddy Opentracing Module (https://github.com/n0trace/caddy-opentracing).

**Comment by yurishkuro** [comment]
Just add it to the registry, it does not need to be in contrib.

Also note that OpenTracing is being retired.

**Comment by tra4less** [comment]
get, do you have detail about retried

**Comment by yurishkuro** [comment]
@tedsuo was going to put up PRs
